server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8  
  context-path: /test
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cnki-GM?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: itec1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate